"""empty message

Revision ID: 00514def17b1
Revises: daf4d572b483
Create Date: 2025-05-05 11:51:06.701315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00514def17b1'
down_revision = 'daf4d572b483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
