"""empty message

Revision ID: 03962397cba2
Revises: 67a497b1cca6
Create Date: 2025-05-05 12:02:58.054816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03962397cba2'
down_revision = '67a497b1cca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('idReserva',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('idReserva',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
