"""empty message

Revision ID: 19309e4cc53f
Revises: 
Create Date: 2025-04-26 00:18:16.243769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19309e4cc53f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('idClub', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('imagen', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('idClub'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('deporte',
    sa.Column('idDeporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('idDeporte')
    )
    op.create_table('horario',
    sa.Column('idHorario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horarioInicio', sa.Time(), nullable=False),
    sa.Column('horarioFin', sa.Time(), nullable=False),
    sa.Column('frecuencia', sa.String(length=50), nullable=True),
    sa.Column('diasDisponibles', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('idHorario')
    )
    op.create_table('rol',
    sa.Column('idRol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('idRol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombreUsuario')
    )
    op.create_table('cancha',
    sa.Column('idCancha', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('idClub', sa.Integer(), nullable=False),
    sa.Column('idHorario', sa.Integer(), nullable=False),
    sa.Column('idDeporte', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idClub'], ['club.idClub'], ),
    sa.ForeignKeyConstraint(['idDeporte'], ['deporte.idDeporte'], ),
    sa.ForeignKeyConstraint(['idHorario'], ['horario.idHorario'], ),
    sa.PrimaryKeyConstraint('idCancha')
    )
    op.create_table('club_deporte',
    sa.Column('idClub', sa.Integer(), nullable=False),
    sa.Column('idDeporte', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idClub'], ['club.idClub'], ),
    sa.ForeignKeyConstraint(['idDeporte'], ['deporte.idDeporte'], ),
    sa.PrimaryKeyConstraint('idClub', 'idDeporte')
    )
    op.create_table('usuario_rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idClub', sa.Integer(), nullable=True),
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idClub'], ['club.idClub'], ),
    sa.ForeignKeyConstraint(['idRol'], ['rol.idRol'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('idReserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCancha', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horaInicio', sa.Time(), nullable=False),
    sa.Column('horaFin', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodoPago', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idCancha'], ['cancha.idCancha'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idReserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('usuario_rol')
    op.drop_table('club_deporte')
    op.drop_table('cancha')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('horario')
    op.drop_table('deporte')
    op.drop_table('club')
    # ### end Alembic commands ###
