"""empty message

Revision ID: 23bf8d110b34
Revises: 288700c54385
Create Date: 2025-04-28 12:35:18.121463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bf8d110b34'
down_revision = '288700c54385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
