"""empty message

Revision ID: 26792fb50f5a
Revises: c749d2b0508d
Create Date: 2025-05-06 14:19:56.599146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26792fb50f5a'
down_revision = 'c749d2b0508d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
