"""empty message

Revision ID: 288700c54385
Revises: 63610bd8b8c0
Create Date: 2025-04-24 19:07:29.219664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288700c54385'
down_revision = '63610bd8b8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))
        batch_op.drop_column('precioXHora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precioXHora', sa.FLOAT(), nullable=False))
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
