"""empty message

Revision ID: 33011b7d3c80
Revises: f48f29db4411
Create Date: 2025-05-12 10:27:34.946374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33011b7d3c80'
down_revision = 'f48f29db4411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
