"""empty message

Revision ID: 3610ee62c7a8
Revises: e51d18c07a96
Create Date: 2025-04-28 18:32:18.154466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3610ee62c7a8'
down_revision = 'e51d18c07a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
