"""empty message

Revision ID: 3ab851e3b595
Revises: d3746c606910
Create Date: 2025-05-02 20:31:28.652404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab851e3b595'
down_revision = 'd3746c606910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
