"""empty message

Revision ID: 3fa1cd1b71db
Revises: ddb9e346b84d
Create Date: 2025-05-01 19:51:37.799249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa1cd1b71db'
down_revision = 'ddb9e346b84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
