"""empty message

Revision ID: 67a497b1cca6
Revises: 00514def17b1
Create Date: 2025-05-05 11:51:14.149025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a497b1cca6'
down_revision = '00514def17b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
