"""Permitir idClub nulo en usuario_rol

Revision ID: 6ebcaa91359a
Revises: c32ba91135dc
Create Date: 2025-04-23 19:26:47.674143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebcaa91359a'
down_revision = 'c32ba91135dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.alter_column('idClub',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.alter_column('idClub',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
