"""empty message

Revision ID: 78d54b5aabd6
Revises: 26792fb50f5a
Create Date: 2025-05-07 16:01:09.965642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d54b5aabd6'
down_revision = '26792fb50f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_id')

    # ### end Alembic commands ###
