"""empty message

Revision ID: 801c69157920
Revises: 3610ee62c7a8
Create Date: 2025-05-01 12:41:21.033447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801c69157920'
down_revision = '3610ee62c7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
