"""empty message

Revision ID: 97138bfd434e
Revises: 03962397cba2
Create Date: 2025-05-05 17:50:07.355635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97138bfd434e'
down_revision = '03962397cba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
