"""empty message

Revision ID: c749d2b0508d
Revises: 97138bfd434e
Create Date: 2025-05-06 12:39:49.743566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c749d2b0508d'
down_revision = '97138bfd434e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
