"""empty message

Revision ID: d3746c606910
Revises: 59ea25d06a14
Create Date: 2025-05-02 19:06:26.122660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3746c606910'
down_revision = '59ea25d06a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
