"""empty message

Revision ID: daf4d572b483
Revises: 3ab851e3b595
Create Date: 2025-05-04 17:20:53.184996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf4d572b483'
down_revision = '3ab851e3b595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
