"""empty message

Revision ID: e51d18c07a96
Revises: 23bf8d110b34
Create Date: 2025-04-28 14:57:27.319553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51d18c07a96'
down_revision = '23bf8d110b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
