"""empty message

Revision ID: ec8031bffe4c
Revises: ccc6a0340937
Create Date: 2025-05-12 20:37:50.639724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8031bffe4c'
down_revision = 'ccc6a0340937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
