"""empty message

Revision ID: f48f29db4411
Revises: 78d54b5aabd6
Create Date: 2025-05-09 11:22:51.850691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48f29db4411'
down_revision = '78d54b5aabd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
